runtime: php55
api_version: 1
threadsafe: true
handlers:

- url: /
  script: login.php

- url: /clientes/.*
  script: clientes.php

- url: /cssLogin\.css
  static_files: cssLogin.css
  upload: cssLogin.css

- url: /vendor/bootstrap/css/
  static_dir: css


- url: /.*
  script: not_found.php
