runtime: php55
api_version: 1
threadsafe: true

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/metal-voyager-246520:us-central1:dbmanantialdeoriente;dbname=dbmanantialdeoriente
  MYSQL_USER: root
  MYSQL_PASSWORD: administrador

handlers:

- url: /
  script: login.php

- url: /login\.php/.*
  script: login.php


- url: /pedidos\.php/.*
  script: pedidos.php

- url: /clientes\.php/.*
  script: clientes.php

- url: /historial\.php/.*
  script: historial.php

- url: /pedidostr\.php/.*
  script: pedidostr.php

- url: /cssLogin\.css
  static_files: cssLogin.css
  upload: cssLogin.css

- url: /funciones\.js
  static_files: funciones.js
  upload: funciones.js

- url: /jquery.dataTables.min\.js
  static_files: jquery.dataTables.min.js
  upload: jquery.dataTables.min.js

- url: /matrix.tables\.js
  static_files: matrix.tables.js
  upload: matrix.tables.js

- url: /vendor
  static_dir: vendor

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

