runtime: php55
api_version: 1
threadsafe: true
handlers:

- url: /
  script: login.php

- url: /stylesheets
  static_dir: stylesheets

- url: /clientes/.*
  script: clientes.php

- url: /.*
  script: not_found.php
